//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CART()
        {
            this.CARTDETAILs = new HashSet<CARTDETAIL>();
        }
    
        public int CARTID { get; set; }
        public string KHACHHANGID { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTDETAIL> CARTDETAILs { get; set; }
    }
}
