//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public string PAYMENTID { get; set; }
        public string ORDERID { get; set; }
        public string PHUONGTHUCTT { get; set; }
        public string TRANGTHAITT { get; set; }
        public Nullable<System.DateTime> NGAYTT { get; set; }
    
        public virtual ORDER ORDER { get; set; }
    }
}
