//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IMAGE
    {
        public int IMAGEID { get; set; }
        public string SANPHAMID { get; set; }
        public string MAUSAC { get; set; }
        public string TENHINH { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
