//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
            this.PRODUCT_COLOR = new HashSet<PRODUCT_COLOR>();
            this.PRODUCT_IMAGE = new HashSet<PRODUCT_IMAGE>();
            this.PRODUCT_SIZE = new HashSet<PRODUCT_SIZE>();
        }
    
        public string SANPHAMID { get; set; }
        public string TENSANPHAM { get; set; }
        public string DANHMUCID { get; set; }
        public decimal GIAGOC { get; set; }
        public decimal GIA { get; set; }
        public int SOLUONGTONKHO { get; set; }
        public string MOTA { get; set; }
        public string HINHANHDAIDIEN { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_COLOR> PRODUCT_COLOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_IMAGE> PRODUCT_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_SIZE> PRODUCT_SIZE { get; set; }
    }
}
