//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LTW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FashionWebEntities : DbContext
    {
        public FashionWebEntities()
            : base("name=FashionWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<CART> CARTs { get; set; }
        public virtual DbSet<CARTDETAIL> CARTDETAILs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<ORDERDETAIL> ORDERDETAILs { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_COLOR> PRODUCT_COLOR { get; set; }
        public virtual DbSet<PRODUCT_IMAGE> PRODUCT_IMAGE { get; set; }
        public virtual DbSet<PRODUCT_SIZE> PRODUCT_SIZE { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
    
        [DbFunction("FashionWebEntities", "FN_DANHSACHDONHANG_KH")]
        public virtual IQueryable<FN_DANHSACHDONHANG_KH_Result> FN_DANHSACHDONHANG_KH(string kHACHHANGID)
        {
            var kHACHHANGIDParameter = kHACHHANGID != null ?
                new ObjectParameter("KHACHHANGID", kHACHHANGID) :
                new ObjectParameter("KHACHHANGID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_DANHSACHDONHANG_KH_Result>("[FashionWebEntities].[FN_DANHSACHDONHANG_KH](@KHACHHANGID)", kHACHHANGIDParameter);
        }
    
        public virtual int SP_CAPNHATTHONGTIN_KHACHHANG(string kHACHHANGID, string hOTEN, Nullable<System.DateTime> nGAYSINH, string eMAIL, string dIENTHOAI)
        {
            var kHACHHANGIDParameter = kHACHHANGID != null ?
                new ObjectParameter("KHACHHANGID", kHACHHANGID) :
                new ObjectParameter("KHACHHANGID", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATTHONGTIN_KHACHHANG", kHACHHANGIDParameter, hOTENParameter, nGAYSINHParameter, eMAILParameter, dIENTHOAIParameter);
        }
    
        public virtual int SP_CAPNHATTONKHOSAUDATHANG(string oRDERID)
        {
            var oRDERIDParameter = oRDERID != null ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATTONKHOSAUDATHANG", oRDERIDParameter);
        }
    
        public virtual int SP_HUYDONHANG(string oRDERID)
        {
            var oRDERIDParameter = oRDERID != null ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HUYDONHANG", oRDERIDParameter);
        }
    
        public virtual int SP_TAODONHANGTUGIOHANG(string orderID, Nullable<int> cartID, string diaChiID)
        {
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            var cartIDParameter = cartID.HasValue ?
                new ObjectParameter("CartID", cartID) :
                new ObjectParameter("CartID", typeof(int));
    
            var diaChiIDParameter = diaChiID != null ?
                new ObjectParameter("DiaChiID", diaChiID) :
                new ObjectParameter("DiaChiID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAODONHANGTUGIOHANG", orderIDParameter, cartIDParameter, diaChiIDParameter);
        }
    
        public virtual int SP_THEMKHACHHANGDIACHI(string kHACHHANGID, string hOTEN, Nullable<System.DateTime> nGAYSINH, string eMAIL, string pASSWORD, string dIENTHOAI)
        {
            var kHACHHANGIDParameter = kHACHHANGID != null ?
                new ObjectParameter("KHACHHANGID", kHACHHANGID) :
                new ObjectParameter("KHACHHANGID", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMKHACHHANGDIACHI", kHACHHANGIDParameter, hOTENParameter, nGAYSINHParameter, eMAILParameter, pASSWORDParameter, dIENTHOAIParameter);
        }
    
        public virtual int SP_THEMSANPHAMMOI(string sANPHAMID, string tENSANPHAM, string dANHMUCID, Nullable<decimal> gIA, string sIZE, string mAUSAC, Nullable<int> sOLUONGTONKHO)
        {
            var sANPHAMIDParameter = sANPHAMID != null ?
                new ObjectParameter("SANPHAMID", sANPHAMID) :
                new ObjectParameter("SANPHAMID", typeof(string));
    
            var tENSANPHAMParameter = tENSANPHAM != null ?
                new ObjectParameter("TENSANPHAM", tENSANPHAM) :
                new ObjectParameter("TENSANPHAM", typeof(string));
    
            var dANHMUCIDParameter = dANHMUCID != null ?
                new ObjectParameter("DANHMUCID", dANHMUCID) :
                new ObjectParameter("DANHMUCID", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var sIZEParameter = sIZE != null ?
                new ObjectParameter("SIZE", sIZE) :
                new ObjectParameter("SIZE", typeof(string));
    
            var mAUSACParameter = mAUSAC != null ?
                new ObjectParameter("MAUSAC", mAUSAC) :
                new ObjectParameter("MAUSAC", typeof(string));
    
            var sOLUONGTONKHOParameter = sOLUONGTONKHO.HasValue ?
                new ObjectParameter("SOLUONGTONKHO", sOLUONGTONKHO) :
                new ObjectParameter("SOLUONGTONKHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMSANPHAMMOI", sANPHAMIDParameter, tENSANPHAMParameter, dANHMUCIDParameter, gIAParameter, sIZEParameter, mAUSACParameter, sOLUONGTONKHOParameter);
        }
    
        public virtual ObjectResult<SP_THONGKEDOANHTHUTHEOTHANG_Result> SP_THONGKEDOANHTHUTHEOTHANG(Nullable<int> nAM)
        {
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKEDOANHTHUTHEOTHANG_Result>("SP_THONGKEDOANHTHUTHEOTHANG", nAMParameter);
        }
    
        public virtual int SP_THONGKEDONHANGTHEOKHACHHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THONGKEDONHANGTHEOKHACHHANG");
        }
    
        public virtual int SP_CAPNHATTONKHOSAUDATHANG1(string oRDERID)
        {
            var oRDERIDParameter = oRDERID != null ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATTONKHOSAUDATHANG1", oRDERIDParameter);
        }
    
        public virtual int SP_CAPNHATTONKHOSAUDATHANG2(string oRDERID)
        {
            var oRDERIDParameter = oRDERID != null ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATTONKHOSAUDATHANG2", oRDERIDParameter);
        }
    }
}
